version: '3.7'
services:
  e2e-local:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
            - ./:/Cypress-Project
      command: ['npm', 'run', 'test', 'local', 'visual']

  e2e-dev:
    build:
      context: .
      dockerfile: Dockerfile
      volumes:
        - ./:/Cypress-Project
      command: ['npm', 'run', 'test', 'dev', 'visual']

