version: '3.7'
services:
  real-world-app:
    build:
      context: ../cypress-realworld-app/
      cache_from:
        - real-world-app:1.0
    volumes:
      - ../cypress-realworld-app/:/app
    ports:
      - "3000:3000"
    command: ['yarn', 'start']

  e2e-qa:
      build:
        context: .
        dockerfile: Dockerfile
#        cache_from:
#          - cypress-project:107
#      depends_on:
#        - real-world-app
##      ports:
##        - "3000:3000"
      volumes:
            - ./:/Cypress-Project
      command: ['yarn', 'run', 'run:qa']

  e2e-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/Cypress-Project
    command: ['yarn', 'run', 'test', 'dev', 'functional']

